apiVersion: v1
kind: Template
metadata:
  name: mock-back-dc-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mock-back
      version: ${VERSION}
      revision: ${REVISION}
    name: mock-back-dc
  spec:
    replicas: 1
    selector:
      app: mock-back
      version: ${VERSION}
      role: app
    template:
      metadata:
        labels:
          app: mock-back
          version: ${VERSION}
          revision: ${REVISION}
          role: app
      spec:
        containers:
        - name: mock-back
          image: docker-registry.default.svc:5000/${PROJECT_NAME}/mock-back:${VERSION}-${REVISION}
          env:
          - name: CONCILIATION_URLS
            value: //${FQDN}/conciliation/
          resources:
            requests:
              cpu: 500m
              memory: 270Mi
            limits:
              cpu: 2000m
              memory: 800Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2

parameters:
- name: PROJECT_NAME
  description: "Project name"
  required: true
- name: VERSION
  description: "Deployment version"
  required: true
- name: REVISION
  description: "Deployment revision"
  required: true
- name: FQDN
  description: "Conciliation Application external route FQDN"
  required: true
