apiVersion: v1
kind: Template
metadata:
  name: mock-front-dc-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mock-front
      version: ${VERSION}
      revision: ${REVISION}
    name: mock-front-dc
  spec:
    replicas: 1
    selector:
      app: mock-front
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    template:
      metadata:
        labels:
          app: mock-front
          version: ${VERSION}
          revision: ${REVISION}
          role: app
      spec:
        containers:
        - name: mock-front
          image: docker-registry.default.svc:5000/${PROJECT_NAME}/mock-front:${VERSION}-${REVISION}
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2

parameters:
- name: PROJECT_NAME
  description: "Project name"
  required: true
- name: VERSION
  description: "Deployment version"
  required: true
- name: REVISION
  description: "Deployment revision"
  required: true
