apiVersion: v1
kind: Template
metadata:
  name: mock-services-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: demo
      version: ${VERSION}
      revision: ${REVISION}
    name: demo
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: demo
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mock-back
      version: ${VERSION}
      revision: ${REVISION}
    name: mock-back
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: mock-back
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mock-front
      version: ${VERSION}
      revision: ${REVISION}
    name: mock-front
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: mock-front
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    type: ClusterIP
parameters:
- name: VERSION
  description: "Service version"
  required: true
- name: REVISION
  description: "Deployment revision"
  required: true
