apiVersion: v1
kind: Template
metadata:
  name: back-dc-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: back
      version: ${VERSION}
      revision: ${REVISION}
    name: back-dc
  spec:
    replicas: 1
    selector:
      app: back
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    template:
      metadata:
        labels:
          app: back
          version: ${VERSION}
          revision: ${REVISION}
          role: app
      spec:
        containers:
        - name: back
          image: docker-repo.techfirm.ch/conciliation/back:${VERSION}
          resources:
            requests:
              cpu: 500m
              memory: 350Mi
            limits:
              cpu: 2000m
              memory: 800Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1

parameters:
- name: PROJECT_NAME
  description: "Project name"
  required: true
- name: VERSION
  description: "Deployment version"
  required: true
- name: REVISION
  description: "Deployment revision"
  required: true
