apiVersion: v1
kind: Template
metadata:
  name: front-dc-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: front
      version: ${VERSION}
      revision: ${REVISION}
    name: front-dc
  spec:
    replicas: 1
    selector:
      app: front
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    template:
      metadata:
        labels:
          app: front
          version: ${VERSION}
          revision: ${REVISION}
          role: app
      spec:
        containers:
        - name: front
          image: docker-repo.techfirm.ch/conciliation/front:${VERSION}
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 100Mi
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1

parameters:
- name: PROJECT_NAME
  description: "Project name"
  required: true
- name: VERSION
  description: "Deployment version"
  required: true
- name: REVISION
  description: "Deployment revision"
  required: true

