apiVersion: v1
kind: Template
metadata:
  name: services-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: back
      version: ${VERSION}
      revision: ${REVISION}
    name: back
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: back
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: front
      version: ${VERSION}
      revision: ${REVISION}
    name: front
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: front
      version: ${VERSION}
      revision: ${REVISION}
      role: app
    type: ClusterIP
parameters:
- name: VERSION
  description: "Service version"
  required: true
- name: REVISION
  description: "Deployment revision"
  required: true
